#ncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'TestMasonry' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Testsonry

pod 'Masonry'
pod 'pop', '~> 1.0.9'
  target 'TestMasonryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestMasonryUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
